"use client";
import { useState } from "react";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/react";
import { Check, X, MoreVertical, LoaderCircle, Search, RefreshCw, Inbox } from "lucide-react";
import { REVIEW_STATUSES, employeeDetails } from "./reviewHelpers";

export function StatusBadge({ status }) {
  const color = { Pending: "bg-amber-50 text-amber-700 ring-amber-600/15", Approved: "bg-emerald-50 text-emerald-700 ring-emerald-600/15", Rejected: "bg-rose-50 text-rose-700 ring-rose-600/15" }[status] || "bg-slate-100 text-slate-600 ring-slate-600/15";
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${color}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
}
function Actions({ item, busy, canDecide, decide }) {
  if (item.displayStatus !== "Pending") return <span className="text-xs text-slate-400">Reviewed</span>;
  if (!canDecide) return <span className="text-xs text-slate-400">View only</span>;
  return <Menu><MenuButton disabled={busy} aria-label={`Actions for ${item.employeeName || "employee"}`} className="grid h-10 w-10 place-items-center rounded-xl text-slate-500 hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-blue-600 disabled:opacity-50">{busy ? <LoaderCircle size={18} className="animate-spin" aria-label="Saving decision" /> : <MoreVertical size={20} />}</MenuButton><MenuItems anchor="bottom end" portal className="z-50 w-40 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl [--anchor-gap:6px] focus:outline-none">{[["approved", "Approve", Check], ["rejected", "Reject", X]].map(([decision, label, Icon]) => <MenuItem key={decision}><button type="button" disabled={busy} onClick={() => decide(item, decision)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm font-medium data-focus:bg-slate-100 ${decision === "approved" ? "text-emerald-700" : "text-rose-700"}`}><Icon size={16} />{label}</button></MenuItem>)}</MenuItems></Menu>;
}
export default function ReviewPanel({ data, columns, canDecide, noun, extraFilters }) {
  const [tab, setTab] = useState("Pending"), [search, setSearch] = useState("");
  const { items, employees, loading, error, busy, message, decide, refresh } = data;
  const searched = items.map((item) => ({ ...item, person: employeeDetails(item, employees) })).filter((item) => `${item.person.name} ${item.person.code}`.toLowerCase().includes(search.toLowerCase()));
  const rows = searched.filter((item) => tab === "All" || item.displayStatus === tab);
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div role="tablist" aria-label={`${noun} status`} className="flex max-w-full gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1 dark:bg-slate-800">{REVIEW_STATUSES.map((status) => <button key={status} type="button" role="tab" aria-selected={tab === status} onClick={() => setTab(status)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium focus-visible:outline-2 focus-visible:outline-blue-600 ${tab === status ? "bg-white text-blue-700 shadow-sm dark:bg-slate-700 dark:text-blue-300" : "text-slate-500 hover:text-slate-800 dark:text-slate-400"}`}>{status}<span className="rounded-md bg-slate-100 px-1.5 py-0.5 text-[11px] tabular-nums text-slate-500 dark:bg-slate-800">{status === "All" ? searched.length : searched.filter((item) => item.displayStatus === status).length}</span></button>)}</div><button type="button" onClick={refresh} disabled={loading} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600 hover:bg-slate-50 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300"><RefreshCw size={15} className={loading ? "animate-spin" : ""} />Refresh</button></div>
    <div className="flex flex-wrap gap-3"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 dark:border-slate-700 dark:bg-slate-900"><Search size={17} className="shrink-0 text-slate-400" /><input aria-label="Search employees" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search employee name or ID" className="w-full bg-transparent py-3 text-sm outline-none dark:text-slate-100" /></label>{extraFilters}</div>
    {error && <div role="alert" className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}<button type="button" onClick={refresh} className="font-semibold underline">Retry</button></div>}
    <p role="status" aria-live="polite" className={message ? "text-sm text-emerald-700" : "sr-only"}>{message}</p>
    <section aria-label={`${tab} ${noun}`} aria-busy={loading} className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900">
      {loading ? <div role="status" aria-label={`Loading ${noun}`} className="space-y-4 p-6">{[0, 1, 2, 3, 4].map((i) => <div key={i} className="flex animate-pulse gap-4"><div className="h-12 w-12 rounded-xl bg-slate-100 dark:bg-slate-800" /><div className="flex-1 space-y-2 py-1"><div className="h-3 w-1/3 rounded bg-slate-100 dark:bg-slate-800" /><div className="h-3 w-2/3 rounded bg-slate-100 dark:bg-slate-800" /></div></div>)}</div> : !rows.length ? <div className="px-6 py-16 text-center"><Inbox size={28} className="mx-auto mb-3 text-slate-300" /><h3 className="font-semibold text-slate-700 dark:text-slate-200">{error ? "Records unavailable" : `No ${tab === "All" ? "" : tab.toLowerCase() + " "}${noun}`}</h3><p className="mt-1 text-sm text-slate-500">{error ? "Retry to load the latest records." : search ? "Try another employee name or ID." : "New records will appear here automatically."}</p></div> : <>
      <div className="hidden overflow-x-auto rounded-2xl lg:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:bg-slate-800"><tr><th scope="col" className="p-4">Employee</th>{columns.map((column) => <th scope="col" key={column.key} className="p-4">{column.label}</th>)}<th scope="col" className="p-4">Status</th><th scope="col" className="p-4"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map((item) => <tr key={item.id} className="align-top hover:bg-slate-50/60 dark:hover:bg-slate-800/40"><td className="min-w-40 p-4"><p className="font-semibold text-slate-800 dark:text-slate-100">{item.person.name}</p><p className="mt-1 text-xs text-slate-400">{item.person.code}</p></td>{columns.map((column) => <td key={column.key} className="p-4 text-slate-600 dark:text-slate-300">{column.render(item)}</td>)}<td className="p-4"><StatusBadge status={item.displayStatus} /></td><td className="p-3"><Actions item={item} busy={busy[item.id]} canDecide={canDecide} decide={decide} /></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-slate-100 lg:hidden dark:divide-slate-800">{rows.map((item) => <article key={item.id} className="p-4"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-800 dark:text-slate-100">{item.person.name}</p><p className="mt-0.5 text-xs text-slate-400">{item.person.code}</p></div><div className="flex items-center gap-2"><StatusBadge status={item.displayStatus} /><Actions item={item} busy={busy[item.id]} canDecide={canDecide} decide={decide} /></div></div><dl className="grid grid-cols-2 gap-4">{columns.map((column) => <div key={column.key} className={column.wide ? "col-span-2" : "min-w-0"}><dt className="mb-1 text-xs text-slate-400">{column.label}</dt><dd className="text-sm text-slate-600 dark:text-slate-300">{column.render(item)}</dd></div>)}</dl></article>)}</div>
      </>}
    </section>
  </div>;
}
