"use client";
import { useEffect, useState } from "react";
import { KeyRound, Lock, LogOut, ShieldCheck, Unlock, UserX } from "lucide-react";
import toast from "react-hot-toast";
import { auth } from "@/lib/firebase";
import { useAuth } from "@/app/(auth)/context/AuthContext";
import activityLogRepository from "@/app/allservice/rbac/activityLogRepository";

const date = (value) => { const current = typeof value?.toDate === "function" ? value.toDate() : value ? new Date(value) : null; return current && !Number.isNaN(current.getTime()) ? current.toLocaleString("en-IN") : "Never"; };
export default function AccessSection({ employee, onChanged }) {
  const { company, access } = useAuth();
  const [logs, setLogs] = useState([]), [busy, setBusy] = useState("");
  useEffect(() => { if (company?.id) activityLogRepository.recent(company.id, 30).then((items) => setLogs(items.filter((item) => item.targetEmployeeId === employee.firestoreId || item.targetUserId === employee.access?.authUid).slice(0, 5))).catch(() => {}); }, [company?.id, employee.firestoreId, employee.access?.authUid]);
  if (!access?.isOwner) return null;
  const ownerAccount = company.ownerUid && employee.access?.authUid === company.ownerUid;
  const action = async (name) => { if (ownerAccount && ["lock", "disable", "delete", "revoke"].includes(name)) return toast.error("The Company Owner account is protected."); setBusy(name); try { const token = await auth.currentUser.getIdToken(); const response = await fetch("/api/rbac/users", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ action: name, targetUid: employee.access?.authUid, employeeFirestoreId: employee.firestoreId, email: employee.email }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); if (result.resetLink) { await navigator.clipboard.writeText(result.resetLink); toast.success("Password reset link copied."); } else toast.success(`Account action completed: ${name}.`); onChanged?.(); } catch (error) { toast.error(error.message || "Account action failed."); } finally { setBusy(""); } };
  const permissions = employee.access?.effectivePermissions || [];
  return <section className="rounded-3xl border border-slate-200 bg-white p-6 xl:col-span-2"><div className="flex items-center gap-3"><ShieldCheck className="text-blue-600"/><div><h2 className="text-xl font-bold">Access & Security</h2><p className="text-sm text-slate-500">Role, permissions, password and session controls</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Info label="Role" value={employee.access?.roleId || employee.role || "Employee"}/><Info label="Account status" value={employee.access?.status || employee.status}/><Info label="Last login" value={date(employee.login?.lastLogin || employee.access?.lastLoginAt)}/><Info label="Permissions" value={ownerAccount ? "Full access" : `${permissions.length} granted`}/></div><div className="mt-5 flex flex-wrap gap-2"><Action icon={KeyRound} label="Reset password" disabled={!employee.access?.authUid || busy} onClick={() => action("reset-password")}/><Action icon={LogOut} label="Force logout" disabled={!employee.access?.authUid || ownerAccount || busy} onClick={() => action("revoke")}/>{employee.access?.status === "locked" ? <Action icon={Unlock} label="Unlock" disabled={busy} onClick={() => action("unlock")}/> : <Action icon={Lock} label="Lock" disabled={!employee.access?.authUid || ownerAccount || busy} onClick={() => action("lock")}/>}<Action icon={KeyRound} label="Expire password" disabled={!employee.access?.authUid || busy} onClick={() => action("expire-password")}/><Action icon={UserX} label="Deactivate" danger disabled={!employee.access?.authUid || ownerAccount || busy} onClick={() => action("disable")}/></div><div className="mt-6"><h3 className="text-sm font-bold">Recent security activity</h3>{logs.length ? <div className="mt-2 space-y-2">{logs.map((item) => <div key={item.id} className="flex justify-between rounded-xl bg-slate-50 p-3 text-xs"><span className="font-semibold">{item.type}</span><span className="text-slate-400">{date(item.createdAt)}</span></div>)}</div> : <p className="mt-2 text-sm text-slate-400">No security activity recorded yet.</p>}</div></section>;
}
function Info({ label, value }) { return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 truncate font-bold capitalize text-slate-700">{value || "—"}</p></div>; }
function Action({ icon: Icon, label, danger, ...props }) { return <button {...props} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold disabled:opacity-40 ${danger ? "border-red-100 bg-red-50 text-red-600" : "bg-white text-slate-700"}`}><Icon size={15}/>{label}</button>; }
