const lower=(value)=>String(value||"").toLowerCase();
const number=(value)=>Number(value||0)||0;
const asDate=(value)=>{if(!value)return null;if(typeof value.toDate==="function")return value.toDate();if(Number.isFinite(value.seconds))return new Date(value.seconds*1000);const result=value instanceof Date?value:new Date(value);return Number.isNaN(result.getTime())?null:result;};
const key=(value)=>{const date=asDate(value);return date?`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`:typeof value==="string"?value.slice(0,10):"";};
const hours=(item)=>{const direct=number(item.totalHours||item.hoursWorked||item.durationHours||item.hours);if(direct)return direct;const start=asDate(item.startTime||item.checkIn),end=asDate(item.endTime||item.checkOut);return start&&end?Math.max(0,(end-start)/3_600_000):0;};
const accepted=(item)=>!["rejected","cancelled","failed","void"].includes(lower(item.status));
export default class ProjectCostService {
  static calculate(data){
    const {project}=data;const employees=project.employees||[];
    const employeeRows=employees.map((employee)=>{const ids=new Set([employee.firestoreId,employee.employeeId].filter(Boolean).map(String));const logs=data.workLogs.filter((item)=>ids.has(String(item.employeeFirestoreId||item.employeeId||item.userId)));const totalHours=logs.reduce((sum,item)=>sum+hours(item),0);const hourlyRate=number(employee.hourlyRate)||number(employee.salary)/208;return{...employee,hours:totalHours,hourlyRate,cost:totalHours*hourlyRate,department:employee.department||"Unassigned"};});
    const employeeCost=employeeRows.reduce((sum,item)=>sum+item.cost,0);const employeeHours=employeeRows.reduce((sum,item)=>sum+item.hours,0);
    const departmentCost=employeeRows.reduce((result,item)=>({...result,[item.department]:(result[item.department]||0)+item.cost}),{});
    const vendorPayments=data.vendorPayments.filter((item)=>["paid","completed","approved"].includes(lower(item.status))||!item.status);const vendorCost=vendorPayments.reduce((sum,item)=>sum+number(item.amount),0);
    const expenses=data.expenses.filter((item)=>accepted(item)&&!["pending","submitted"].includes(lower(item.status))&&!item.vendorPaymentId&&!lower(item.module).includes("vendor-payment")&&!lower(item.type).includes("vendor payment"));
    const expenseCost=expenses.reduce((sum,item)=>sum+number(item.amount),0);const actualCost=employeeCost+vendorCost+expenseCost;
    const budget=number(project.approvedBudget||project.budget);const contract=number(project.contractValue||project.poAmount);
    const vendorAssignments=(project.vendors||[]).map((assignment)=>{const ids=new Set([assignment.firestoreId,assignment.vendorId].filter(Boolean).map(String));const paid=vendorPayments.filter((item)=>ids.has(String(item.vendorId))).reduce((sum,item)=>sum+number(item.amount),0);const allocated=number(assignment.allocatedAmount||assignment.contractValue);return{...assignment,allocatedAmount:allocated,paidAmount:paid,remainingAmount:Math.max(0,allocated-paid),paymentPercent:allocated?paid/allocated*100:0};});
    const daily={};const add=(date,amount)=>{const day=key(date);if(day)daily[day]=(daily[day]||0)+amount;};expenses.forEach((item)=>add(item.date||item.createdAt,number(item.amount)));vendorPayments.forEach((item)=>add(item.date||item.createdAt,number(item.amount)));data.workLogs.forEach((log)=>{const employee=employeeRows.find((item)=>[item.firestoreId,item.employeeId].filter(Boolean).map(String).includes(String(log.employeeFirestoreId||log.employeeId||log.userId)));add(log.date||log.startTime||log.createdAt,hours(log)*number(employee?.hourlyRate));});
    let cumulative=0;const profitTrend=Object.entries(daily).sort(([a],[b])=>a.localeCompare(b)).map(([date,cost])=>{cumulative+=cost;return{label:date.slice(5),value:contract-cumulative,cost};}).slice(-30);
    const today=key(new Date()),month=today.slice(0,7);const todayCost=number(daily[today]);const monthlyCost=Object.entries(daily).filter(([date])=>date.startsWith(month)).reduce((sum,[,amount])=>sum+amount,0);
    return{employeeCost,employeeHours,averageCostPerHour:employeeHours?employeeCost/employeeHours:0,departmentCost,employeeRows,vendorCost,vendorPayments,vendorAssignments,expenseCost,expenses,actualCost,todayCost,monthlyCost,budget,remainingBudget:budget-actualCost,budgetUsed:budget?actualCost/budget*100:0,contract,expectedProfit:contract-actualCost,expectedLoss:Math.max(0,actualCost-contract),profitPercent:contract?(contract-actualCost)/contract*100:0,costMix:[{label:"Employee",value:employeeCost},{label:"Vendor",value:vendorCost},{label:"Expenses",value:expenseCost}],profitTrend,vendorPaymentTrend:vendorPayments.sort((a,b)=>(asDate(a.date||a.createdAt)||0)-(asDate(b.date||b.createdAt)||0)).map((item)=>({label:key(item.date||item.createdAt).slice(5),value:number(item.amount)})).slice(-30)};
  }
}
