"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import {
  AlertTriangle, BadgeIndianRupee, Building2, CheckCircle2, ChevronLeft,
  ChevronRight, Eye, FolderKanban, LayoutGrid, List, Pencil, Plus, RefreshCw,
  Search, Trash2, TrendingUp,
} from "lucide-react";
import { neo, StatCard } from "@/app/(dashboard)/manager/dashboard/DashboardWidgets";

const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const statusStyle = { running: "bg-blue-50 text-blue-700", completed: "bg-emerald-50 text-emerald-700", pending: "bg-amber-50 text-amber-700", hold: "bg-slate-100 text-slate-600", "on hold": "bg-slate-100 text-slate-600", delayed: "bg-red-50 text-red-700" };

export default function ProjectPortfolioDashboard({ projects, allProjects, clients, loading, refreshing, error, filters, onFilter, onRefresh, onCreate, onEdit, onDelete, onStatus, busyId }) {
  const router = useRouter(); const [view, setView] = useState("table"); const [page, setPage] = useState(1); const pageSize = 10;
  const pages = Math.max(1, Math.ceil(projects.length / pageSize));
  useEffect(() => { setPage(1); }, [filters.search, filters.status, filters.client, filters.intelligence]);
  const visible = projects.slice((page - 1) * pageSize, page * pageSize);
  const stats = {
    total: allProjects.length,
    running: allProjects.filter((item) => String(item.status).toLowerCase() === "running").length,
    completed: allProjects.filter((item) => String(item.status).toLowerCase() === "completed").length,
    delayed: allProjects.filter((item) => item.overdue || String(item.status).toLowerCase() === "delayed" || (item.endDate && item.endDate < new Date().toISOString().slice(0,10) && String(item.status).toLowerCase() !== "completed")).length,
    budget: allProjects.reduce((sum,item)=>sum+Number(item.budget||0),0),
    profit: allProjects.reduce((sum,item)=>sum+Number(item.totalProfit ?? Number(item.poAmount||0)-Number(item.totalExpense||0)),0),
  };
  const cards = [["Total Projects",stats.total,FolderKanban,"blue"],["Running",stats.running,LayoutGrid,"violet"],["Completed",stats.completed,CheckCircle2,"green"],["Delayed",stats.delayed,AlertTriangle,"red"],["Portfolio Budget",stats.budget,BadgeIndianRupee,"amber","currency"],["Portfolio Profit",stats.profit,TrendingUp,stats.profit>=0?"green":"red","currency"]];
  const smart = [["all","All"],["delayed","Delayed"],["critical","High Risk"],["loss","Loss"],["profit","High Profit"],["budget","Budget Exceeded"],["vendor","High Vendor Cost"]];
  return <div className="space-y-6 px-2 py-2 sm:px-4 lg:px-6">
    <header className={`${neo} rounded-3xl bg-white p-5 sm:p-6`}><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-600 text-white"><FolderKanban size={24}/></span><div><h1 className="text-2xl font-bold text-slate-800 sm:text-3xl">Project Management</h1><p className="mt-1 text-sm text-slate-500">Plan, monitor and control your project portfolio</p></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>router.push("/manager/clients")} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600"><Building2 size={17}/>Manage clients</button><button onClick={onRefresh} disabled={refreshing} aria-label="Refresh projects" className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white"><RefreshCw size={17} className={refreshing?"animate-spin":""}/></button><button onClick={onCreate} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-blue-200"><Plus size={17}/>New project</button></div></div></header>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
    <section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{cards.map(([title,value,Icon,tone,format])=><StatCard key={title} title={title} value={value} icon={Icon} tone={tone} format={format}/>)}</section>
    <section className={`${neo} rounded-3xl p-4 sm:p-5`}><div className="flex flex-col gap-3 xl:flex-row xl:items-center"><div className="relative flex-1"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={filters.search} onChange={(event)=>onFilter("search",event.target.value)} placeholder="Search project, ID, client, manager or employee..." className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-11 pr-3 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50"/></div><select value={filters.status} onChange={(event)=>onFilter("status",event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-600"><option value="all">All statuses</option><option value="pending">Pending</option><option value="running">Running</option><option value="completed">Completed</option><option value="hold">On Hold</option><option value="delayed">Delayed</option></select><select value={filters.client} onChange={(event)=>onFilter("client",event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-600"><option value="">All clients</option>{clients.map((item)=><option key={item.id} value={item.id}>{item.clientName||item.companyName}</option>)}</select><div className="flex rounded-xl border border-slate-200 bg-white p-1"><button onClick={()=>setView("table")} className={`grid h-8 w-9 place-items-center rounded-lg ${view==="table"?"bg-blue-50 text-blue-600":"text-slate-400"}`}><List size={16}/></button><button onClick={()=>setView("grid")} className={`grid h-8 w-9 place-items-center rounded-lg ${view==="grid"?"bg-blue-50 text-blue-600":"text-slate-400"}`}><LayoutGrid size={16}/></button></div></div><div className="mt-4 flex max-w-full gap-2 overflow-x-auto pb-1">{smart.map(([value,label])=><button key={value} onClick={()=>onFilter("intelligence",value)} className={`shrink-0 rounded-xl px-3.5 py-2 text-xs font-bold ${filters.intelligence===value?"bg-slate-800 text-white":"bg-white text-slate-600"}`}>{label}</button>)}</div></section>
    {loading ? <div className="space-y-3">{Array.from({length:6},(_,index)=><div key={index} className="h-20 animate-pulse rounded-2xl bg-white/70"/>)}</div> : !visible.length ? <div className={`${neo} grid min-h-72 place-items-center rounded-3xl text-center`}><div><FolderKanban className="mx-auto text-slate-300" size={42}/><h2 className="mt-4 text-lg font-bold text-slate-700">No projects found</h2><p className="mt-1 text-sm text-slate-500">Change the filters or create a new project.</p><button onClick={onCreate} className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Create project</button></div></div> : view === "table" ? <div className={`${neo} overflow-hidden rounded-3xl`}><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="border-b border-slate-200 bg-white/60 text-left text-[11px] uppercase tracking-wider text-slate-400"><tr><th className="p-4">Project</th><th>Client</th><th>Status</th><th>Timeline</th><th>Progress</th><th>Budget</th><th>Expense</th><th>Profit</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody>{visible.map((project)=><ProjectTableRow key={project.id} project={project} busy={busyId===project.id} onView={()=>router.push(`/manager/projects/${project.id}`)} onEdit={()=>onEdit(project)} onDelete={()=>onDelete(project)} onStatus={(status)=>onStatus(project,status)}/>)}</tbody></table></div></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((project)=><ProjectGridCard key={project.id} project={project} busy={busyId===project.id} onView={()=>router.push(`/manager/projects/${project.id}`)} onEdit={()=>onEdit(project)} onDelete={()=>onDelete(project)} onStatus={(status)=>onStatus(project,status)}/>)}</div>}
    {projects.length>pageSize&&<div className="flex items-center justify-between"><p className="text-sm text-slate-500">Showing {(page-1)*pageSize+1}–{Math.min(page*pageSize,projects.length)} of {projects.length}</p><div className="flex items-center gap-2"><button disabled={page===1} onClick={()=>setPage((value)=>value-1)} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white disabled:opacity-40"><ChevronLeft size={17}/></button><span className="text-sm font-bold text-slate-600">{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage((value)=>value+1)} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white disabled:opacity-40"><ChevronRight size={17}/></button></div></div>}
  </div>;
}

function ProjectTableRow({project,busy,onView,onEdit,onDelete,onStatus}) { const profit=Number(project.totalProfit ?? Number(project.poAmount||0)-Number(project.totalExpense||0)); return <tr className="border-b border-slate-100 transition hover:bg-white"><td className="p-4"><button onClick={onView} className="text-left"><span className="block max-w-48 truncate font-bold text-slate-800 hover:text-blue-600">{project.projectName}</span><span className="text-xs text-slate-400">{project.projectId}</span></button></td><td className="max-w-36 truncate">{project.clientName||"—"}</td><td><select disabled={busy} value={project.status||"Pending"} onChange={(event)=>onStatus(event.target.value)} className={`rounded-lg px-2 py-1.5 text-xs font-bold outline-none ${statusStyle[String(project.status||"pending").toLowerCase()]||statusStyle.pending}`}><option>Pending</option><option>Running</option><option>Completed</option><option>Hold</option><option>Delayed</option></select></td><td className="text-xs text-slate-500">{project.startDate||"—"}<br/>{project.endDate||"—"}</td><td><div className="w-24"><div className="mb-1 text-xs font-bold">{Number(project.progress||0)}%</div><div className="h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(100,Number(project.progress||0))}%`}}/></div></div></td><td>{money(project.budget)}</td><td>{money(project.totalExpense)}</td><td className={profit<0?"font-bold text-red-600":"font-bold text-emerald-600"}>{money(profit)}</td><td className="pr-4"><ActionGroup busy={busy} onView={onView} onEdit={onEdit} onDelete={onDelete}/></td></tr>; }
function ProjectGridCard({project,busy,onView,onEdit,onDelete,onStatus}) { const profit=Number(project.totalProfit ?? Number(project.poAmount||0)-Number(project.totalExpense||0)); return <article className={`${neo} rounded-3xl p-5 transition hover:-translate-y-1`}><div className="flex items-start justify-between gap-3"><button onClick={onView} className="min-w-0 text-left"><h2 className="truncate text-lg font-bold text-slate-800 hover:text-blue-600">{project.projectName}</h2><p className="mt-1 truncate text-xs text-slate-400">{project.projectId} • {project.clientName||"No client"}</p></button><select disabled={busy} value={project.status||"Pending"} onChange={(event)=>onStatus(event.target.value)} className={`rounded-lg px-2 py-1.5 text-xs font-bold outline-none ${statusStyle[String(project.status||"pending").toLowerCase()]||statusStyle.pending}`}><option>Pending</option><option>Running</option><option>Completed</option><option>Hold</option><option>Delayed</option></select></div><div className="mt-5 grid grid-cols-3 gap-2"><Small label="Budget" value={money(project.budget)}/><Small label="Expense" value={money(project.totalExpense)}/><Small label="Profit" value={money(profit)} tone={profit<0?"text-red-600":"text-emerald-600"}/></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs font-bold text-slate-500"><span>Progress</span><span>{Number(project.progress||0)}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(100,Number(project.progress||0))}%`}}/></div></div><div className="mt-5 flex justify-end"><ActionGroup busy={busy} onView={onView} onEdit={onEdit} onDelete={onDelete}/></div></article>; }
function ActionGroup({busy,onView,onEdit,onDelete}) { return <div className="flex justify-end gap-1"><button disabled={busy} onClick={onView} title="View project" className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-blue-600 disabled:opacity-40"><Eye size={15}/></button><button disabled={busy} onClick={onEdit} title="Edit project" className="grid h-8 w-8 place-items-center rounded-lg bg-amber-50 text-amber-600 disabled:opacity-40"><Pencil size={15}/></button><button disabled={busy} onClick={onDelete} title="Delete project" className="grid h-8 w-8 place-items-center rounded-lg bg-red-50 text-red-600 disabled:opacity-40"><Trash2 size={15}/></button></div>; }
function Small({label,value,tone="text-slate-800"}) { return <div className="min-w-0 rounded-xl bg-white p-3"><p className="truncate text-[10px] font-semibold text-slate-400">{label}</p><p className={`mt-1 truncate text-xs font-bold ${tone}`}>{value}</p></div>; }
