"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Banknote, CalendarDays, CircleDollarSign, FileText, Plus, Search, Wallet } from "lucide-react";
import { useAuth } from "@/app/(auth)/context/AuthContext";
import { EmptyState, neo } from "@/app/(dashboard)/manager/dashboard/DashboardWidgets";
import useBillingData from "./hooks/useBillingData";
import PaymentDialog from "./components/PaymentDialog";
import { money } from "./components/InvoiceDocument";

const periodStart = (period) => { const now = new Date(); if (period === "month") return new Date(now.getFullYear(), now.getMonth(), 1); if (period === "quarter") return new Date(now.getFullYear(), Math.floor(now.getMonth() / 3) * 3, 1); if (period === "fy") return new Date(now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1, 3, 1); return null; };
const asDate = (value) => value?.toDate?.() || (value ? new Date(value) : null);

export default function BillingPage() {
  const { company } = useAuth();
  const router = useRouter();
  const data = useBillingData(company?.id);
  const [tab, setTab] = useState("invoices");
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [period, setPeriod] = useState("all");
  const [payment, setPayment] = useState(null);
  const invoices = useMemo(() => {
    const query = search.trim().toLowerCase();
    const start = periodStart(period);
    return data.analytics.invoices.filter((item) => {
      const haystack = `${item.invoiceNumber} ${item.clientName} ${item.projectName} ${item.poNumber || ""} ${item.clientSnapshot?.gstNumber || ""}`.toLowerCase();
      const date = asDate(item.invoiceDate || item.createdAt);
      return (!query || haystack.includes(query)) && (status === "all" || item.displayStatus === status) && (!start || (date && date >= start));
    });
  }, [data.analytics.invoices, search, status, period]);
  const projects = data.analytics.projects;
  const summary = data.analytics.summary;
  const metrics = [["Total Invoiced", summary.totalInvoiced, FileText, "text-indigo-600 bg-indigo-50"], ["Total Received", summary.collected, Banknote, "text-emerald-600 bg-emerald-50"], ["Outstanding", summary.outstanding, Wallet, "text-amber-600 bg-amber-50"], ["Overdue", summary.overdue, CalendarDays, "text-rose-600 bg-rose-50"]];
  return <div className="space-y-5 px-2 py-2 sm:px-5">
    <header className={`${neo} flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 lg:flex-row lg:items-center lg:justify-between`}><div><h1 className="text-2xl font-bold text-slate-900">Billing & Invoices</h1><p className="text-sm text-slate-500">Issue invoices, collect payments and track receivables</p></div><button onClick={() => router.push("/manager/billing/new")} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white"><Plus size={17} />Create Invoice</button></header>
    {data.error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Billing data could not be loaded. Please try again.</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon, tone]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{label}</span><span className={`grid h-9 w-9 place-items-center rounded-xl ${tone}`}><Icon size={17} /></span></div><strong className="mt-3 block text-xl text-slate-900">₹ {money(value)}</strong></article>)}</section>
    <section className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{[["Draft", summary.draft], ["Running", summary.running], ["Partial", summary.partialInvoices], ["Paid", summary.paidInvoices], ["Overdue", summary.overdueInvoices], ["Cancelled", summary.cancelled]].map(([label, count]) => <button key={label} onClick={() => { setTab("invoices"); setStatus(label.toLowerCase()); }} className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-left shadow-sm"><span className="text-xs text-slate-500">{label}</span><strong className="block text-lg text-slate-800">{count}</strong></button>)}</section>
    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1">{[["invoices", "Invoices"], ["clients", "Customer Billing"], ["projects", "Project Billing"]].map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`shrink-0 rounded-lg px-4 py-2 text-sm font-semibold ${tab === id ? "bg-indigo-600 text-white" : "text-slate-600 hover:bg-slate-50"}`}>{label}</button>)}</nav>
    {tab === "invoices" && <><section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 lg:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search invoice, customer, project, PO or GSTIN" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-indigo-500" /></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold"><option value="all">All statuses</option>{["draft", "running", "partial", "paid", "overdue", "cancelled"].map((value) => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select><select value={period} onChange={(event) => setPeriod(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold"><option value="all">All dates</option><option value="month">This month</option><option value="quarter">This quarter</option><option value="fy">This financial year</option></select></section>{data.loading ? <Loading /> : <InvoiceTable invoices={invoices} onOpen={(item) => router.push(`/manager/billing/${item.id}`)} onEdit={(item) => router.push(`/manager/billing/new?editId=${item.id}`)} onPayment={setPayment} onCreate={() => router.push("/manager/billing/new")} />}</>}
    {tab === "clients" && <ClientLedgers clients={data.analytics.clients} onOpen={(invoice) => router.push(`/manager/billing/${invoice.id}`)} />}
    {tab === "projects" && <div className="grid gap-4 xl:grid-cols-2">{projects.length ? projects.map((project) => <ProjectCard key={project.id} project={project} onCreate={() => router.push(`/manager/billing/new?projectId=${project.id}`)} />) : <EmptyState label="No completed projects available for billing" />}</div>}
    <PaymentDialog open={Boolean(payment)} onClose={() => setPayment(null)} companyId={company?.id} invoice={payment} />
  </div>;
}

function InvoiceTable({ invoices, onOpen, onEdit, onPayment, onCreate }) { return invoices.length ? <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b bg-slate-50 text-left text-[11px] uppercase tracking-wide text-slate-500"><th className="p-4">Invoice No.</th><th>Customer</th><th>Invoice Date</th><th>Due Date</th><th className="text-right">Amount</th><th className="text-right">Paid</th><th className="text-right">Balance</th><th>Status</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody>{invoices.map((item) => <tr key={item.id} className="border-b last:border-0 hover:bg-slate-50/70"><td className="p-4"><button onClick={() => onOpen(item)} className="font-bold text-indigo-600">{item.invoiceNumber}</button><span className="block text-[11px] text-slate-400">{item.projectName}</span></td><td><strong className="font-semibold text-slate-800">{item.clientName}</strong><span className="block text-[11px] text-slate-400">{item.clientSnapshot?.gstNumber || ""}</span></td><td>{item.invoiceDate || "—"}</td><td className={item.overdue ? "font-semibold text-rose-600" : ""}>{item.dueDate || "—"}</td><td className="text-right font-semibold">₹ {money(item.receivable ?? item.invoiceAmount)}</td><td className="text-right text-emerald-700">₹ {money(item.paid)}</td><td className="text-right font-bold">₹ {money(item.pending)}</td><td><StatusBadge status={item.displayStatus} /></td><td className="pr-4"><div className="flex justify-end gap-2"><button onClick={() => onOpen(item)} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold">View</button>{item.invoiceStatus !== "cancelled" && item.paymentStatus !== "paid" && <button onClick={() => item.invoiceStatus === "draft" ? onEdit(item) : onPayment(item)} className="rounded-lg bg-indigo-50 px-2.5 py-1.5 text-xs font-bold text-indigo-700">{item.invoiceStatus === "draft" ? "Edit" : "Record Payment"}</button>}</div></td></tr>)}</tbody></table></div> : <div className="rounded-2xl border border-slate-200 bg-white py-16 text-center"><CircleDollarSign className="mx-auto text-slate-300" size={38} /><h2 className="mt-3 font-bold text-slate-800">No invoices yet</h2><p className="mt-1 text-sm text-slate-500">Create your first invoice to start tracking billing and payments.</p><button onClick={onCreate} className="mt-4 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Create Invoice</button></div>; }
function StatusBadge({ status }) { const tones = { draft: "bg-slate-100 text-slate-600", running: "bg-blue-50 text-blue-700", partial: "bg-amber-50 text-amber-700", paid: "bg-emerald-50 text-emerald-700", overdue: "bg-rose-50 text-rose-700", cancelled: "bg-slate-200 text-slate-600" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${tones[status] || tones.draft}`}>{status}</span>; }
function ClientLedgers({ clients, onOpen }) { return <div className="grid gap-4 lg:grid-cols-2">{clients.length ? clients.map((client) => <article key={client.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="font-bold text-slate-900">{client.name}</h2><p className="text-xs text-slate-400">{client.gstNumber || "No GSTIN"}</p></div><span className="text-xs font-semibold text-slate-500">{client.invoices.length} invoice(s)</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Small label="Invoiced" value={client.billed} /><Small label="Received" value={client.paid} /><Small label="Outstanding" value={client.outstanding} /><Small label="Overdue" value={client.overdue} /></div><div className="mt-4 space-y-2">{client.invoices.slice(0, 3).map((invoice) => <button key={invoice.id} onClick={() => onOpen(invoice)} className="flex w-full justify-between rounded-lg bg-slate-50 px-3 py-2 text-xs"><span className="font-semibold text-indigo-600">{invoice.invoiceNumber}</span><span>₹ {money(invoice.pending)} due</span></button>)}</div></article>) : <EmptyState label="No customer billing activity" />}</div>; }
function ProjectCard({ project, onCreate }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="font-bold">{project.projectName}</h2><p className="text-xs text-slate-400">{project.clientName} · {project.projectId}</p></div><StatusBadge status={project.billingStatus === "ready" ? "running" : project.billingStatus} /></div><div className="mt-4 grid grid-cols-3 gap-2"><Small label="Contract" value={project.contractValue} /><Small label="Billed" value={project.billedAmount} /><Small label="Remaining" value={project.remainingBillable} /></div>{project.remainingBillable > 0 && project.billingStatus !== "cancelled" && <button onClick={onCreate} className="mt-4 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Create Invoice</button>}</article>; }
function Small({ label, value }) { return <div className="rounded-lg bg-slate-50 p-2"><span className="block text-[10px] uppercase text-slate-400">{label}</span><strong className="text-xs">₹ {money(value)}</strong></div>; }
function Loading() { return <div className="space-y-2">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-16 animate-pulse rounded-xl bg-white" />)}</div>; }
