"use client";

import { useEffect, useMemo, useState } from "react";
import { BanknoteArrowDown, Building2, CheckCircle2, Download, Plus, RefreshCw, Search, UserRound, WalletCards } from "lucide-react";
import toast from "react-hot-toast";
import { useAuth } from "@/app/(auth)/context/AuthContext";
import { StatCard, neo } from "../dashboard/DashboardWidgets";
import AddAdvanceModal from "./components/AddAdvanceModal";
import AdvanceService from "./services/AdvanceService";

const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;
const asDate = (value) => { if (!value) return null; if (typeof value?.toDate === "function") return value.toDate(); const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const date = (value) => asDate(value)?.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) || "—";
const lower = (value) => String(value || "").toLowerCase();

export default function AdvancePage() {
  const { company, currentUser } = useAuth();
  const [records, setRecords] = useState([]), [employees, setEmployees] = useState([]), [projects, setProjects] = useState([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [modal, setModal] = useState(null);
  const [search, setSearch] = useState(""), [status, setStatus] = useState("all"), [type, setType] = useState("all");

  useEffect(() => {
    if (!company?.id) return;
    AdvanceService.getReferenceData(company.id).then(({ employees: people, projects: work }) => { setEmployees(people); setProjects(work); }).catch(() => setError("Unable to load employees and projects."));
    const unsubscribe = AdvanceService.subscribe(company.id, (items) => { setRecords(items); setLoading(false); setError(""); }, () => { setError("Unable to load advance requests."); setLoading(false); });
    return unsubscribe;
  }, [company?.id]);

  const filtered = useMemo(() => records.filter((item) => {
    const text = search.trim().toLowerCase();
    return (!text || `${item.employeeName} ${item.employeeId} ${item.projectName} ${item.reason} ${item.purpose}`.toLowerCase().includes(text)) && (status === "all" || lower(item.status) === status) && (type === "all" || lower(item.advanceType) === type);
  }), [records, search, status, type]);
  const summary = useMemo(() => ({ total: records.reduce((sum, item) => sum + Number(item.amount || 0), 0), pending: records.filter((item) => lower(item.status) === "pending").length, personal: records.filter((item) => lower(item.advanceType) === "personal").reduce((sum, item) => sum + Number(item.remainingAmount ?? item.amount ?? 0), 0), company: records.filter((item) => lower(item.advanceType) === "company").reduce((sum, item) => sum + Number(item.remainingAmount ?? item.amount ?? 0), 0), settled: records.filter((item) => lower(item.status) === "settled").length }), [records]);

  const changeStatus = async (item, next) => { const remarks = prompt(`${next} remarks (optional):`) || ""; try { await AdvanceService.setStatus(company.id, item, next, remarks, currentUser); toast.success(`Advance ${next.toLowerCase()}.`); } catch (e) { console.error(e); toast.error("Unable to update request."); } };
  const settle = async (item) => { const value = prompt(`Settlement amount (remaining ${money(item.remainingAmount ?? item.amount)}):`); if (!value || Number(value) <= 0) return; try { await AdvanceService.recordSettlement(company.id, item, Number(value)); toast.success("Settlement recorded."); } catch { toast.error("Unable to record settlement."); } };
  const remove = async (item) => { if (!confirm(`Delete ${item.employeeName}'s advance?`)) return; try { await AdvanceService.delete(company.id, item.id); toast.success("Advance deleted."); } catch { toast.error("Unable to delete advance."); } };
  const exportExcel = async () => { const XLSX = await import("xlsx"); const rows = filtered.map((item) => ({ Request_ID: item.requestId || item.id, Employee: item.employeeName, Employee_ID: item.employeeId, Type: item.advanceType, Amount: item.amount, Monthly_Deduction: item.monthlyDeduction, Remaining: item.remainingAmount, Settled: item.settledAmount, Project: item.projectName, Status: item.status, Requested: date(item.requestedAt || item.createdAt) })); const sheet = XLSX.utils.json_to_sheet(rows), workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, "Advance Requests"); XLSX.writeFile(workbook, `advance-requests-${new Date().toISOString().slice(0, 10)}.xlsx`); };

  return <div className="space-y-6 px-2 py-2 sm:px-5"><header className={`${neo} flex flex-col gap-5 rounded-3xl bg-white p-5 lg:flex-row lg:items-center lg:justify-between`}><div className="flex items-center gap-4"><span className="grid h-13 w-13 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 text-white"><BanknoteArrowDown/></span><div><h1 className="text-2xl font-bold text-slate-800 sm:text-3xl">Advance Management</h1><p className="text-sm text-slate-500">Personal salary advances and company work funds</p></div></div><div className="flex flex-wrap gap-2"><button onClick={exportExcel} disabled={!filtered.length} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-bold disabled:opacity-40"><Download size={17}/>Export</button><button onClick={() => window.location.reload()} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-bold"><RefreshCw size={17}/>Refresh</button><button onClick={() => setModal({})} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white"><Plus size={17}/>Add Advance</button></div></header>

    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
    <section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5"><StatCard title="Total Advanced" value={summary.total} icon={WalletCards} format="currency"/><StatCard title="Pending Requests" value={summary.pending} icon={BanknoteArrowDown} tone="amber"/><StatCard title="Personal Outstanding" value={summary.personal} icon={UserRound} tone="violet" format="currency"/><StatCard title="Company Outstanding" value={summary.company} icon={Building2} tone="blue" format="currency"/><StatCard title="Settled" value={summary.settled} icon={CheckCircle2} tone="green"/></section>

    <section className={`${neo} grid gap-3 rounded-3xl p-4 sm:grid-cols-3`}><label className="relative sm:col-span-1"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search employee, project, purpose..." className="h-11 w-full rounded-xl border bg-white pl-10 pr-3 text-sm"/></label><select value={type} onChange={(e) => setType(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm"><option value="all">All advance types</option><option value="personal">Personal</option><option value="company">Company work</option></select><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm"><option value="all">All statuses</option>{["pending","approved","rejected","settled"].map((item) => <option key={item} value={item}>{item}</option>)}</select></section>

    <section className={`${neo} overflow-hidden rounded-3xl`}>{loading ? <div className="space-y-3 p-6">{Array.from({ length: 5 }, (_, i) => <div key={i} className="h-16 animate-pulse rounded-2xl bg-slate-200"/>)}</div> : !filtered.length ? <div className="py-20 text-center text-slate-500">No advance requests found.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-100 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Employee</th><th>Type / Purpose</th><th>Amount</th><th>Repayment</th><th>Remaining</th><th>Requested</th><th>Status</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t border-slate-100 bg-white hover:bg-slate-50"><td className="p-4"><p className="font-bold text-slate-800">{item.employeeName}</p><p className="text-xs text-slate-400">{item.employeeId} • {item.department || "No department"}</p></td><td><p className="font-semibold">{item.advanceType || "Personal"}</p><p className="max-w-48 truncate text-xs text-slate-400">{item.projectName || item.reason || item.purpose || "—"}</p></td><td className="font-bold">{money(item.amount)}</td><td>{lower(item.advanceType) === "personal" ? <><p>{money(item.monthlyDeduction)}/month</p><p className="text-xs text-slate-400">{item.months || 0} months</p></> : <span>Expense settlement</span>}</td><td className="font-bold text-red-600">{money(item.remainingAmount ?? item.amount)}</td><td>{date(item.requestedAt || item.createdAt)}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${lower(item.status) === "approved" ? "bg-green-50 text-green-700" : lower(item.status) === "rejected" ? "bg-red-50 text-red-700" : lower(item.status) === "settled" ? "bg-blue-50 text-blue-700" : "bg-amber-50 text-amber-700"}`}>{item.status || "Pending"}</span></td><td className="pr-4"><div className="flex justify-end gap-2">{lower(item.status) === "pending" && <><button onClick={() => changeStatus(item, "Approved")} className="rounded-lg bg-green-50 px-3 py-2 font-bold text-green-700">Approve</button><button onClick={() => changeStatus(item, "Rejected")} className="rounded-lg bg-red-50 px-3 py-2 font-bold text-red-700">Reject</button></>}{lower(item.status) === "approved" && Number(item.remainingAmount ?? item.amount) > 0 && <button onClick={() => settle(item)} className="rounded-lg bg-blue-50 px-3 py-2 font-bold text-blue-700">Settle</button>}<button onClick={() => setModal(item)} className="rounded-lg bg-slate-100 px-3 py-2 font-bold">Edit</button><button onClick={() => remove(item)} className="rounded-lg px-3 py-2 font-bold text-red-600">Delete</button></div></td></tr>)}</tbody></table></div>}</section>
    {modal && <AddAdvanceModal companyId={company.id} employees={employees} projects={projects} existing={modal.id ? modal : null} onClose={() => setModal(null)}/>} </div>;
}
